version: "3.9"

services:
  #Mongodb services
  mongo_db:
    # we can call it whatever
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - mongo_db:/data/db
    #Node JS api service
    # api:
    #   build: .
    #   ports:
    #     - 4000:3000
    #     # local:container
    #   volumes:
    #     - .:/usr/src/app
    #     - /usr/src/app/node_modules
    #     # this makes it so the node modules are not over written by local node_modules

    #     # you may need to run docker-compose build once you map a src volume
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      # we could give it any db name
      NAME: Kevin Mason
    # localhost becomes the service name
  #   depends_on:
  #     - mongo_db

volumes:
  mongo_db: {}
